### ISSUE TITLE
cloudant.Document marshal to JSON and unmarshal back again is lossy

### ISSUE THREAD

**Issue by dnwe** [IBM/cloudant-go-sdk#122]
**Describe the bug**

If you marshal a `cloudant.Document` to JSON it correctly includes all properties of the document. However, if you then unmarshal it back to a `cloudant.Document` again, it has lost all of the custom properties. This is because a custom `MarshalJSON()` func has been implemented for Document and it handles the `additionalProperties` map, but there isn't a custom `UnmarshalJSON()` so it just relies on the json struct tags and doesn't correctly unmarshal the `additionalProperties` out

**To Reproduce**

```go
package main

import (
	"encoding/json"
	"testing"

	cloudant "github.com/IBM/cloudant-go-sdk/cloudantv1"
	"github.com/IBM/go-sdk-core/v4/core"
	assert "github.com/stretchr/testify/require"
)

// TestDocument_RoundtripJSON ensures that a `cloudant.Document` can be
// roundtripped to JSON and back again, retaining all fields.
func TestDocument_RoundtripJSON(t *testing.T) {
    const expectedJSON = `{"_id":"1234","value":"abcd"}`

    want := &cloudant.Document{
        ID: core.StringPtr("1234"),
    }
    want.SetProperty("value", "abcd")

    wantJSON, _ := json.Marshal(want)
    assert.JSONEq(t, expectedJSON, string(wantJSON), "documents should marshal to JSON with all properties")

    var got cloudant.Document
    _ = json.Unmarshal(wantJSON, &got)

    assert.Equal(t, want, got, "documents should be equal after JSON marshal+unmarshal roundtrip")
}
```

**Expected behavior**

It should be possible to roundtrip a `cloudant.Document` struct to and from JSON out of the box.

**Screenshots**

N/A

**Must gather (please complete the following information):**
go1.15
github.com/IBM/cloudant-go-sdk v0.0.30
github.com/IBM/go-sdk-core/v4 v4.10.0

**Additional context**

N/A

**Comment by mojito317** [comment]
Hi @dnwe!

Do you want to specifically use the JSON unmarshalling or the following solution with `UnmarshalDocument` is also appropriate for your goals?
```go
package main

import (
	"encoding/json"
	cloudant "github.com/IBM/cloudant-go-sdk/cloudantv1"
	"github.com/IBM/go-sdk-core/v4/core"
	assert "github.com/stretchr/testify/require"
	"testing"
)

func TestDocument_RoundtripJSON(t *testing.T) {
	const expectedJSON = `{"_id":"1234","value":"abcd"}`

	want := &cloudant.Document{
		ID: core.StringPtr("1234"),
	}
	want.SetProperty("value", "abcd")

	wantJSON, _ := json.Marshal(want)
	assert.JSONEq(t, expectedJSON, string(wantJSON), "documents should marshal to JSON with all properties")

	var objmap map[string]json.RawMessage
	json.Unmarshal(wantJSON, &objmap)

	var got *cloudant.Document
	_ = cloudant.UnmarshalDocument(objmap, &got)

	assert.Equal(t, want, got, "documents should be equal after JSON marshal+unmarshal roundtrip")
}
```

**Comment by dnwe** [comment]
@mojito317 ah thanks for the pointer!

I _think_ I can use this as a workaround in my app, I will give it a try shortly.

It might still be useful to have the built-in Unmarshal <--> Marshal flow working too, just by putting a call to UnmarshalDocument in as a custom `func (d *Document) UnmarshalJSON(...) { ... }` func, because that would allow it to work when a `cloudant.Document` is embedded in some parent struct

**Comment by mojito317** [comment]
> It might still be useful to have the built-in Unmarshal <--> Marshal flow working too

Thanks, @dnwe, we need to take this into consideration.

Our getter functions already return with an unmarshalled Document, see the example under the [Retrieve a document section](https://cloud.ibm.com/apidocs/cloudant?code=go#getdocument) in our API Docs. 

If you do not want to stick with the `Document` struct you can use the stream methods instead. There are not many examples for that in our API Docs and maybe we should've highlighted them more but you can find one under the [Bulk docs](https://cloud.ibm.com/apidocs/cloudant?code=go#postbulkdocs), one under the [Changes feed](https://cloud.ibm.com/apidocs/cloudant?code=go#postchanges), and another one under [All docs](https://cloud.ibm.com/apidocs/cloudant?code=go#postalldocs) just search for `Example request as a stream` statement.

**Comment by dnwe** [comment]
@mojito317 just to clarify what I meant in the earlier comment.

I was proposing that it would be useful if the types had a custom UnmarshalJSON added to them that proxied to the existing functions you have.

i.e., for `cloudant.Document`:
```diff
diff --git a/cloudantv1/cloudant_v1.go b/cloudantv1/cloudant_v1.go
index b033b18..1e839ad 100644
--- a/cloudantv1/cloudant_v1.go
+++ b/cloudantv1/cloudant_v1.go
@@ -9940,6 +9941,20 @@ func (o *Document) MarshalJSON() (buffer []byte, err error) {
 	return
 }
 
+// UnmarshalJSON performs custom serialization for instances of Document
+func (o *Document) UnmarshalJSON(data []byte) error {
+	var m map[string]json.RawMessage
+	if err := json.Unmarshal(data, &m); err != nil {
+		return err
+	}
+	var d *Document
+	if err := UnmarshalDocument(m, &d); err != nil {
+		return err
+	}
+	*o = *d
+	return nil
+}
+
 // UnmarshalDocument unmarshals an instance of Document from the specified map of raw messages.
 func UnmarshalDocument(m map[string]json.RawMessage, result interface{}) (err error) {
 	obj := new(Document)
```
