### ISSUE TITLE
Update Golang version to 1.17

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-go-sdk#242]
**Is your feature request related to a problem? Please describe.**

No, update of oldest supported version of Golang.

**Describe the solution you'd like**

Update to Golang 1.17

**Describe alternatives you've considered**

N/A

**Additional context**

1.18 will be released in Feb after which 1.16 will no longer be supported.

**Comment by vmatyusGitHub** [comment]
Is it a possibility to wait with this update till 1.18 released?

**Comment by emlaver** [comment]
We could do that or just merge the PR I have and open a new ticket to add 1.18 to our testing matrix, etc

**Comment by eiri** [comment]
I'm with @vmatyusGitHub on this one. As of today golang has two stable version 1.17 and 1.6 and 1.18 is still marked as unstable: https://go.dev/dl/

Merging the PR  makes sdk not compatible with 1.16, so we'll essentially only support 1.17
```
…/github.com/IBM/cloudant-go-sdk on  242-update-golang [?] $ go mod tidy
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
```

I'd prefer us to sit on the merging this PR till 1.18 goes stable, so we are on minimal supported version, not on maximum one.

**Comment by emlaver** [comment]
Sound good, let's wait until the release of 1.18.

**Comment by emlaver** [comment]
1.18 release now expected this month.

**Comment by vmatyusGitHub** [comment]
d) Set `typecheck` package as disabled till compatibility got not corrected. 

But I personally vote for b), after the lint correction published it will work fine, it will be fixed in 2-4 weeks. 🤞 Can we wait that much?

**Comment by emlaver** [comment]
I'm fine with holding off for a couple weeks until it's fixed.  I'm also fine with merging what we have (just 1.17) and then adding in 1.18 once it's fixed.
@mojito317 FYI

**Comment by vmatyusGitHub** [comment]
> I'm also fine with merging what we have (just 1.17) and then adding in 1.18 once it's fixed.

Agree. Let's keep 1.16 and 1.17 for now and update the mod to 1.17.
After create an issue to update to 1.18 after the lint have a released fix. Even the PR can be prepared and can be moved under the `Blocked` coloumn.

**Comment by emlaver** [comment]
Ok I'd be fine with that.  @eiri @mojito317 wdyt?

**Comment by eiri** [comment]
I think we can't bump mod to 1.17 and keep 1.16 at the same time `go mod tidy` will just block install on 1.16.

**Comment by emlaver** [comment]
@eiri @mojito317 PR is now green after updating golang linter to latest version: https://github.com/IBM/cloudant-go-sdk/pull/245
