### ISSUE TITLE
How can we convert response of dbClient.PostFind(postFindOptions) into struct?

### ISSUE THREAD

**Issue by munesh005** [IBM/cloudant-go-sdk#298]
I am unable to convert the response into struct. below is my code ..
findResult, _, err := dbClient.PostFind(postFindOptions)
	if err != nil {
		fmt.Println("err", err)
	}
	b, _ := json.MarshalIndent(findResult, "", "  ")

how can we convert findResult into struct? please suggest the solution.

Thanks in advanced!

**Comment by ricellis** [comment]
The `findResult` is a [FindResult](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#FindResult) struct, that is what is returned by [PostFind](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#CloudantV1.PostFind).

**Comment by munesh005** [comment]
Thanks Rich for your quick reply. Actually I am getting 'Docs' from FindResult struct and want to have docs values in my customized struct where i can apply my logic.

**Comment by ricellis** [comment]
>Actually I am getting 'Docs' from FindResult struct and want to have docs values in my customized struct where i can apply my logic.

Sorry that wasn't clear to me from the original question.

You have 2 choices:
1. write a converter to accept the built-in [`Document`](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#Document) struct type and use [`GetProperty`](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#Document.GetProperty)/[`GetProperties`](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#Document.GetProperties) to retrieve the properties you need and apply them to your own struct type.
2. use [raw IO](https://github.com/IBM/cloudant-go-sdk#raw-io) with [`PostFindAsStream`](https://pkg.go.dev/github.com/IBM/cloudant-go-sdk@v0.1.4/cloudantv1#CloudantV1.PostFindAsStream) to bypass the built-in types and deserialize directly into your own structs.
