### ISSUE TITLE
How can we use both couch as well as cloudant DB at time in Golang ? 

### ISSUE THREAD

**Issue by munesh005** [IBM/cloudant-go-sdk#306]
Hi , I am using both (couch and cloudant db) in my Golang App. but both databases have different code to insert, update and query data. So is there any compatibility to use both databases together with minimal changes?

**Comment by emlaver** [comment]
@munesh005 this library is compatible with both CouchDB and Cloudant.  For more information on the differences, see the [API comparison guide](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-comparison-of-ibm-cloudant-and-couchdb-api-endpoints) for a detailed breakdown of the API endpoints.
>  both databases have different code to insert, update and query data

It's the same API call to create and modify docs.  What API are you using to query data? The `_find` endpoint is supported in both CouchDB and Cloudant and you'll see more details in the link above.

**Comment by munesh005** [comment]
ok... Thanks Esteban for your quick reply. will see through the link which you have shared.
