### ISSUE TITLE
fix lint action

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-go-sdk#376]
The golangci/golangci-lint-action is not permitted by the org (unverified publisher).
We need to change our workflow to lint differently.

Disabling linting my be the first step while we investigate alternatives.

```
 Error: .github#L1
golangci/golangci-lint-action@v3 is not allowed to be used in IBM/cloudant-go-sdk. Actions in this workflow must be: within a repository owned by IBM, created by GitHub, or verified in the GitHub Marketplace.
```

**Comment by eiri** [comment]
I think we can switch to using https://github.com/marketplace/actions/super-linter which is verified on the Github Marketplace and uses the same [golangci-lint](https://github.com/golangci/golangci-lint) under the hood

**Comment by eiri** [comment]
It seems that super-linter is [unusable](https://github.com/github/super-linter/issues/143) for golang, so this is a dead end

**Comment by eiri** [comment]
There is an open req to have it enabled: https://github.ibm.com/open-source/github-actions-compliance/issues/13

So let's see how it goes, I'll keep https://github.com/IBM/cloudant-go-sdk/pull/379 open for test proposes in case it get addressed in speedy fashion
