### ISSUE TITLE
Feature: session authenticator

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-go-sdk#4]
**Is your feature request related to a problem? Please describe.**
Automatic CouchDB session cookie management.

**Describe the solution you'd like**
Authenticator for CouchDB's `_session` endpoint, like those available in the Node, Java and Python SDKs.

**Describe alternatives you've considered**
The IAM authenticator is preferred for the Cloudant services.
For CouchDB the basic authenticator is usable as a workaround, but the performance is not as good as a session cookie under some security settings.

**Additional context**

**Comment by mojito317** [comment]
With this feature, the README should be updated as well. There should be a description of session authentication, and the preferred authentication type should be changed from Basic to Cookie as well.

Example from the Java SDK:
* https://github.com/IBM/cloudant-java-sdk/blame/master/README.md#L48
* https://github.com/IBM/cloudant-java-sdk/blame/master/README.md#L167-L171
* https://github.com/IBM/cloudant-java-sdk/blame/master/README.md#L201-L213
* https://github.com/IBM/cloudant-java-sdk/blame/master/README.md#L227-L228

**Comment by mojito317** [comment]
The README generator can handle the missing parts from the README. See the https://github.com/IBM/cloudant-go-sdk/compare/generated-readme-template-2 branch.
