### ISSUE TITLE
panic on closed pipe

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-go-sdk#54]
**Describe the bug**

There is a panic when a read/write is attempted on a closed pipe when using compressed request bodies
```
panic: io: read/write on closed pipe
goroutine 6 [running]:
github.com/IBM/go-sdk-core/v4/core.NewGzipCompressionReader.func1(0xc0000104e0, 0x161e500, 0xc000371770)
        /Users/ildiko/go/pkg/mod/github.com/!i!b!m/go-sdk-core/v4@v4.8.1/core/gzip.go:44 +0x11f
created by github.com/IBM/go-sdk-core/v4/core.NewGzipCompressionReader
        /Users/ildiko/go/pkg/mod/github.com/!i!b!m/go-sdk-core/v4@v4.8.1/core/gzip.go:30 +0x152
```

**To Reproduce**
No reproduce yet, but presumably any closed pipe would trigger it.

**Expected behavior**
I think a panic is excessive, connections being closed seems like a quite likely condition to encounter. This should probably return an error or as a last resort maybe we need a recover somewhere. It would be good to align the behaviour with whatever happens with a closed pipe in the uncompressed case - and if that is a panic (though I hope it isn't) then we should document how to handle that situation.

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version 0.0.27
 - Go Version 1.14.3
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
It seems like the core issues this panic
https://github.com/IBM/go-sdk-core/blob/ab65711ec6e580aa84ddaf5bc2609e27646bac3f/v4/core/gzip.go#L44

**Comment by eiri** [comment]
So, basically what's happening here is that there is a race between `service.Client.Do` call and compressing goroutine that's trying to pipe from closed request's body reader and raises panic.

A ticket raised with core-sdk team to fix this.

**Comment by ricellis** [comment]
OK, closing there is no further action for us to take here - we'll get the updated core, when it is available, via a dependabot PR anyway.
