### ISSUE TITLE
Any example of query documents by selector?

### ISSUE THREAD

**Issue by mailtokun** [IBM/cloudant-go-sdk#66]
for example: how to query name is `tom` in `users` document. Thanks.
```
Document name: users

{
  "name":"tom",
  "age":19
}
{
  "name":"alex",
  "age":18
}
```

**Comment by emlaver** [comment]
Hi @mailtokun, our [Cloudant Query documentation](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-query) contains information on how to create an index.

[Here's a code sample in our API documentation](https://cloud.ibm.com/apidocs/cloudant?code=go#postfind) for querying a Cloudant Query index.

**Comment by emlaver** [comment]
Closing as stale.
