### ISSUE TITLE
Linter updates

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-go-sdk#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Select a group of linters from https://golangci-lint.run/usage/linters/ (assuming we stay with golangci-lint), get consensus on the selection and enable them in travis.

**Describe alternatives you've considered**

**Additional context**
Couple of notes:
* decide whether all linters should be disabled on generated code
* prefer built-in fixers so that manual changes are minimal (this should help with the reviews)

**Comment by bessbd** [comment]
The linters should be okay as-is. I'm closing this ticket with no action.
